# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: |
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      # github.com:22 SSH-2.0-babeld-4f04c79d
      github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDt7d4of5iPQ7IgBVEUvSfVQuzLwyX1pfs7GUhmbqEzhhBDOqp0eBP4fGIUKZgR0T37O8h4JDtSS8u41d4pNZeibRHLC1ucLW0EK0G1Y9TK/p/lmHt3uJuli+oCkzOoog5ir2jd0EenKOQB4rIh70S5VywCLdP5xww4fIUCG9zEiZA/uebIG7SOGq5zNYeFF5CRwibMrLlXlATAAPMbmT3bN9a4VJy2RAz1xfjph2zqVq0MuUb2IUKPOW5YswH0u2ySrA6DBiXzoCpd2VDN1YLKmYlKM9OzD+a/QXsadkYG0TvJTJRPr/o5uvSg8Ulsl/g8JK6+bEwpF9tEY2C87UlH p.saucy@PCP265'
    sshKeySecureFile: '-----BEGIN OPENSSH PRIVATE KEY----- b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn NhAAAAAwEAAQAAAQEA7e3eKH+Yj0OyIAVRFL0n1ULsy8Ml9aX7OxlIZm6hM4YQQzqqdHgT +HxiFCmYEdE9+zvIeCQ7UkvLuNXeKTWXom0RywtbnC1tBCtBtWPUyv6f5Zh7d7ibpYvqAp MzqKIOYq9o3dBHpyjkAeKyIe9EuVcsAi3T+ccMOHyFAhvcxImQP7nmyBu0jhquczWHhReQ kcImzKy5V5QEwADzG5k92zfWuFSctkQM9cX46Yds6latDLlG9iFCjzluWLMB9LtskqwOgw Yl86AqXdlQzdWCypmJSjPTsw/mv0F7GnZGBtE7yUyUT6/6Obr0oPFJbJf4PCSuvmxMKRfb RGNgvO1JRwAAA8iPYdR8j2HUfAAAAAdzc2gtcnNhAAABAQDt7d4of5iPQ7IgBVEUvSfVQu zLwyX1pfs7GUhmbqEzhhBDOqp0eBP4fGIUKZgR0T37O8h4JDtSS8u41d4pNZeibRHLC1uc LW0EK0G1Y9TK/p/lmHt3uJuli+oCkzOoog5ir2jd0EenKOQB4rIh70S5VywCLdP5xww4fI UCG9zEiZA/uebIG7SOGq5zNYeFF5CRwibMrLlXlATAAPMbmT3bN9a4VJy2RAz1xfjph2zq Vq0MuUb2IUKPOW5YswH0u2ySrA6DBiXzoCpd2VDN1YLKmYlKM9OzD+a/QXsadkYG0TvJTJ RPr/o5uvSg8Ulsl/g8JK6+bEwpF9tEY2C87UlHAAAAAwEAAQAAAQEAotGUpcIrdF6vFpqM 0dRf3eDeitIQt/nN4rN6iB5M0iV8G4WZ//nsMK9trr6IAilecP6IQS8KKVcVIne4gBrcmZ pqArjTCB1N7PxtCuQ2SnPUmBmw5EzAtpj4mqqBP3UmwwGmkaRmZE3nOiMYI4DJVswAob0a wmMkScNsgfTvLs5iwAWcXWJmSRKX3CDKFV//VMfe5rRXcRxCskvDwlE48Z/S8bqtWLVvKz kD0NagoKv9tEFLNSnrCtaygdW5OileNRQPnHOCugoyb5bDhx/qfSXTO+yW2j52jXXAOMd8 rXAi6pDs5jPmztCUdG1eZQwBg6xD1Xt9LjUf0llo4/3JgQAAAIEAuDxAjkhs943lf7rz79 tCEdWyBmE0Uvv7X21fAlzHAv+gRY0Pf3W1p21sToPbKKx+iQUKq4Rm0pzvWeYbLs2Ll9MQ 4gJr/kFd6x/0IAfJa0ZNLZaNtcoyzm9vqgu/SQLNpQfjigD4seqoLMg8tGEjq6vPOHHV/G efGRfsKlkhyh0AAACBAPuUgE/7lfdYHD3gQTxRSF5ig26OQ23UN7reY87QwH90HglyEy1Z UfLq4R+Em4MIw7qAE8DDeMVPeJwnlij9uGFMhB+z55e725qF/AFPwh/Urq8Nokn+H7HITS BZV5wMmYfEj3Qh0vrUJC1ZINH3QNW0g2ZQfPo50uIR+phCXu6LAAAAgQDyG/h9qnaOqHjR TPIQ/VGW5SJ6PQXYreZEgEOaZNj0FsVi3YNKLBFiGUcJAzq5QGUEcuWkNXXMrfq9aTvtmz WvUBkcSfD8d87nAhkdRcvdiw8Ea+D605hXmi8AhywO9gjZOGj3rdAjF3WD8PLKdtVoZk6V 9ZCYS5d00OggFGkDtQAAAA5wLnNhdWN5QFBDUDI2NQECAw== -----END OPENSSH PRIVATE KEY-----'